default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: mafianarrator_development

test:
  <<: *default
  database: mafianarrator_test

production:
  <<: *default
  database: mafianarrator_production
  username: nelsonsupholstery
  password: <%= ENV['NELSONSUPHOLSTERY_DATABASE_PASSWORD'] %>